name: Update npm downloads

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Fetch npm downloads
        run: node fetch-downloads.js

      - name: Commit and push changes
        run: |
          git config --local user.email "mohamedhany.mh.1999@gmail.com"
          git config --local user.name "Mohamed Hany"
          git add downloads.md
          git commit -m "Update npm downloads"
          git push https://username:${{ secrets.PAT }}@github.com/Hensh99/memvigil.git HEAD:main
